version: "3"
services:
    api:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "CHANGEME123!"
            ACCEPT_EULA: "Y"
    ui:
        build: ui
        ports:
            - "3000:3000"
        stdin_open: true
        depends_on:
            - api