version: "3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000;https://0.0.0.0:5001"
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      SA_PASSWORD: "CHANGEME123!"
      ACCEPT_EULA: "Y"
  ui:
    build: ui
    ports:
      - "3000:3000"
    stdin_open: true
